/**
 * Create the three-wallet .env the rail needs, without a private key ever
 * passing through a terminal argument or a chat window.
 *
 *   RELAYER_PK=0x... node scripts/setup-wallets.mjs
 *
 * The payer key is generated here and written straight to .env. It is never
 * printed - only its address is, because that is the part you need in order to
 * fund it.
 *
 * Why a fresh payer rather than reusing the funded deployer: settle.ts asserts
 * the payer's native balance is exactly zero, and you cannot drain an account to
 * exactly zero - the drain transaction burns gas and leaves dust. A wallet that
 * has never received C2FLR is the only one that satisfies a strict equality
 * against zero.
 *
 * Existing values in .env are kept. Re-running this will not rotate a payer key
 * you have already funded.
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { generatePrivateKey, privateKeyToAccount } from "viem/accounts";
import { getAddress } from "viem";

const ENV_PATH = new URL("../.env", import.meta.url);
const FACILITATOR = "0x43F672C0a915F59A2472a07D2108936e217cB04C";
const RPC_URL = "https://coston2-api.flare.network/ext/C/rpc";

/** Minimal .env parser - enough for KEY=value, which is all this file ever is. */
function readEnv(path) {
  if (!existsSync(path)) return {};
  const out = {};
  for (const raw of readFileSync(path, "utf8").split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq === -1) continue;
    out[line.slice(0, eq).trim()] = line.slice(eq + 1).trim();
  }
  return out;
}

const isSet = (v) => typeof v === "string" && v !== "" && v !== "0x";

const existing = readEnv(ENV_PATH);

// --- relayer: supplied, never generated -------------------------------------
const relayerPk = process.env.RELAYER_PK ?? existing.RELAYER_PK;
if (!isSet(relayerPk)) {
  console.error(
    "\nRELAYER_PK is not set.\n\n" +
      "  RELAYER_PK=0x<deployer key> node scripts/setup-wallets.mjs\n\n" +
      "The relayer is the wallet that already holds C2FLR and pays every gas fee.\n",
  );
  process.exit(1);
}
const relayerKey = relayerPk.startsWith("0x") ? relayerPk : `0x${relayerPk}`;
const relayer = privateKeyToAccount(relayerKey);

// --- payer: generated once, then left alone ---------------------------------
const payerPk = isSet(existing.PAYER_PK) ? existing.PAYER_PK : generatePrivateKey();
const payer = privateKeyToAccount(payerPk);
const reusedPayer = isSet(existing.PAYER_PK);

// The payee only ever receives, so it is safe for it to be the relayer. Keeping
// it separate is tidier for a demo but costs another funded wallet.
const payee = isSet(existing.PAYEE_ADDRESS)
  ? getAddress(existing.PAYEE_ADDRESS)
  : relayer.address;

const contents = `# Generated by scripts/setup-wallets.mjs. Gitignored - never commit this.
RPC_URL=${existing.RPC_URL ?? RPC_URL}

# PAYER holds FXRP and deliberately ZERO C2FLR. That zero is the whole proof:
# it is what makes the payment gasless from the agent's side. Never send this
# address native gas - settle.ts checks the balance is exactly 0.
PAYER_PK=${payerPk}

# RELAYER holds C2FLR only. It pays every gas fee.
RELAYER_PK=${relayerKey}

# PAYEE just receives.
PAYEE_ADDRESS=${payee}

# Deployed and source-verified on Coston2.
FACILITATOR_ADDRESS=${existing.FACILITATOR_ADDRESS ?? FACILITATOR}
`;

writeFileSync(ENV_PATH, contents, { encoding: "utf8" });

console.log("\n.env written\n");
console.log(`  payer      ${payer.address}   ${reusedPayer ? "(kept existing key)" : "(new key)"}`);
console.log(`  relayer    ${relayer.address}`);
console.log(`  payee      ${payee}`);
console.log(`  facilitator ${existing.FACILITATOR_ADDRESS ?? FACILITATOR}`);
console.log(
  "\nNext: fund the payer with FXRP from the relayer.\n" +
    "  npm run fund -- 2\n\n" +
    "Do not send the payer any C2FLR.\n",
);
